REATE TABLE `cliente` (
  `CPF` varchar(11) NOT NULL,
  `NOME` varchar(100) DEFAULT NULL,
  `ENDERECO1` varchar(150) DEFAULT NULL,
  `ENDERECO2` varchar(150) DEFAULT NULL,
  `BAIRRO` varchar(50) DEFAULT NULL,
  `CIDADE` varchar(50) DEFAULT NULL,
  `ESTADO` varchar(2) DEFAULT NULL,
  `CEP` varchar(8) DEFAULT NULL,
  `DATANASCIMENTO` date DEFAULT NULL,
  `IDADE` smallint(6) DEFAULT NULL,
  `SEXO` varchar(1) DEFAULT NULL,
  `LIMITECREDITO` float DEFAULT NULL,
  `VOLUMECOMPRA` float DEFAULT NULL,
  `PRIMEIRACOMPRA` bit(1) DEFAULT NULL,
  PRIMARY KEY (`CPF`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Produtos` (
                            `PRODUTO` varchar(20) NOT NULL,
                            `NOME` varchar(150) DEFAULT NULL,
                            `EMBALAGEM` varchar(50) DEFAULT NULL,
                            `TAMANHO` varchar(50) DEFAULT NULL,
                            `SABOR` varchar(50) DEFAULT NULL,
                            `PRECO_LISTA` float DEFAULT NULL,
                            PRIMARY KEY (`PRODUTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `vendedores` (
                              `ID_MATRICULA` varchar(5) NOT NULL,
                              `VENDEDOR` varchar(100) DEFAULT NULL,
                              `PERCENTUAL_COMISSAO` float DEFAULT NULL,
                              `DATA_ADIMISSAO` date DEFAULT NULL,
                              `DE_FERIAS` bit(1) DEFAULT NULL,
                              PRIMARY KEY (`ID_MATRICULA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `cliente` (`CPF`, `NOME`, `ENDERECO1`, `ENDERECO2`, `BAIRRO`, `CIDADE`, `ESTADO`, `CEP`, `DATANASCIMENTO`, `IDADE`, `SEXO`, `LIMITECREDITO`, `VOLUMECOMPRA`, `PRIMEIRACOMPRA`) VALUES ('1471151234', 'Gloria Junqueira', 'R. Pirituba', 'Rondonia, 21', 'Vila Margarida', 'São Paulo', 'SP', '82912135', '1997-08-31', '22', NULL, '170000', '245000', b'0'),
                                                                                                                                                                                                  ('1471156710', 'Érica Carvalho', 'R. Iriquitia', '', 'Jardins', 'São Paulo', 'SP', '80012212', '1990-09-01', '27', 'F', '170000', '245000', b'0'),
                                                                                                                                                                                                  ('1471156713', 'Marcelina Carvalho', 'R. Golçalvez', 'Amarila, 21', 'Vila Mercedes', 'São Paulo', 'SP', '82912212', '1990-08-31', '27', NULL, '170000', '245000', b'0'),
                                                                                                                                                                                                  ('19290992743', 'Fernando Cavalcante', 'R. Dois de Fevereiro', '', 'Água Santa', 'Rio de Janeiro', 'RJ', '22000000', '2000-02-12', '18', 'M', '100000', '200000', b'1'),
                                                                                                                                                                                                  ('2600586709', 'César Teixeira', 'Rua Conde de Bonfim', '', 'Tijuca', 'Rio de Janeiro', 'RJ', '22020001', '2000-03-12', '18', 'M', '120000', '220000', b'0'),
                                                                                                                                                                                                  ('3623344710', 'Marcos Nougeuira', 'Av. Pastor Martin Luther King Junior', '', 'Inhauma', 'Rio de Janeiro', 'RJ', '22002012', '1995-01-13', '23', 'M', '110000', '220000', b'1'),
                                                                                                                                                                                                  ('492472718', 'Eduardo Jorge', 'R. Volta Grande', '', 'Tijuca', 'Rio de Janeiro', 'RJ', '22012002', '1994-07-19', '23', 'M', '75000', '95000', b'1'),
                                                                                                                                                                                                  ('50534475787', 'Abel Silva ', 'Rua Humaitá', '', 'Humaitá', 'Rio de Janeiro', 'RJ', '22000212', '1995-09-11', '22', 'M', '170000', '260000', b'0'),
                                                                                                                                                                                                  ('5576228758', 'Petra Oliveira', 'R. Benício de Abreu', '', 'Lapa', 'São Paulo', 'SP', '88192029', '1995-11-14', '22', 'F', '70000', '160000', b'1'),
                                                                                                                                                                                                  ('5648641702', 'Paulo César Mattos', 'Rua Hélio Beltrão', '', 'Tijuca', 'Rio de Janeiro', 'RJ', '21002020', '1991-08-30', '26', 'M', '120000', '220000', b'0'),
                                                                                                                                                                                                  ('5840119709', 'Gabriel Araujo', 'R. Manuel de Oliveira', '', 'Santo Amaro', 'São Paulo', 'SP', '80010221', '1985-03-16', '32', 'M', '140000', '210000', b'1'),
                                                                                                                                                                                                  ('7771579779', 'Marcelo Mattos', 'R. Eduardo Luís Lopes', '', 'Brás', 'São Paulo', 'SP', '88202912', '1992-03-25', '25', 'M', '120000', '200000', b'1'),
                                                                                                                                                                                                  ('8502682733', 'Valdeci da Silva', 'R. Srg. Édison de Oliveira', '', 'Jardins', 'São Paulo', 'SP', '82122020', '1995-10-07', '22', 'M', '110000', '190000', b'0'),
                                                                                                                                                                                                  ('8719655770', 'Carlos Eduardo', 'Av. Gen. Guedes da Fontoura', '', 'Jardins', 'São Paulo', 'SP', '81192002', '1983-12-20', '34', 'M', '200000', '240000', b'0'),
                                                                                                                                                                                                  ('9283760794', 'Edson Meilelles', 'R. Pinto de Azevedo', '', 'Cidade Nova', 'Rio de Janeiro', 'RJ', '22002002', '1995-10-07', '22', 'M', '150000', '250000', b'1'),
                                                                                                                                                                                                  ('94387575700', 'Walber Lontra', 'R. Cel. Almeida', '', 'Piedade', 'Rio de Janeiro', 'RJ', '22000201', '1989-06-20', '28', 'M', '60000', '120000', b'1'),
                                                                                                                                                                                                  ('95939180787', 'Fábio Carvalho', 'R. dos Jacarandás da Península', '', 'Barra da Tijuca', 'Rio de Janeiro', 'RJ', '22002020', '1992-01-05', '16', 'M', '90000', '180000', b'1');

INSERT INTO `Produtos` (`PRODUTO`, `NOME`, `EMBALAGEM`, `TAMANHO`, `SABOR`, `PRECO_LISTA`)
VALUES ('1000889', 'Sabor da Montanha - 700 ml - Uva', 'Garrafa', '700 ml', 'Uva', '6.309'),
                                                                                                  ('1002334', 'Linha Citros - 1 Litro - Lima/Limão', 'PET', '1 Litro', 'Lima/Limão', '7.004'),
                                                                                                  ('1002767', 'Videira do Campo - 700 ml - Cereja/Maça', 'Garrafa', '700 ml', 'Cereja/Maça', '8.41'),
                                                                                                  ('1004327', 'Videira do Campo - 1,5 Litros - Melância', 'PET', '1,5 Litros', 'Melância', '19.51'),
                                                                                                  ('1013793', 'Videira do Campo - 2 Litros - Cereja/Maça', 'PET', '2 Litros', 'Cereja/Maça', '24.01'),
                                                                                                  ('1022450', 'Festival de Sabores - 2 Litros - Açai', 'PET', '2 Litros', 'Açai', '38.012'),
                                                                                                  ('1037797', 'Clean - 2 Litros - Laranja', 'PET', '2 Litros', 'Laranja', '16.008'),
                                                                                                  ('1040107', 'Light - 350 ml - Melância', 'Lata', '350 ml', 'Melância', '4.555'),
                                                                                                  ('1041119', 'Linha Citros - 700 ml - Lima/Limão', 'Garrafa', '700 ml', 'Lima/Limão', '4.904'),
                                                                                                  ('1042712', 'Linha Citros - 700 ml - Limão', 'Garrafa', '700 ml', 'Limão', '4.904'),
                                                                                                  ('1051518', 'Frescor do Verão - 470 ml - Limão', 'Garrafa', '470 ml', 'Limão', '3.2995'),
                                                                                                  ('1078680', 'Frescor do Verão - 470 ml - Manga', 'Garrafa', '470 ml', 'Manga', '5.1795'),
                                                                                                  ('1086543', 'Linha Refrescante - 1 Litro - Manga', 'PET', '1 Litro', 'Manga', '11.0105'),
                                                                                                  ('1088126', 'Linha Citros - 1 Litro - Limão', 'PET', '1 Litro', 'Limão', '7.004'),
                                                                                                  ('1096818', 'Linha Refrescante - 700 ml - Manga', 'Garrafa', '700 ml', 'Manga', '7.7105'),
                                                                                                  ('1101035', 'Linha Refrescante - 1 Litro - Morango/Limão', 'PET', '1 Litro', 'Morango/Limão', '9.0105'),
                                                                                                  ('229900', 'Pedaços de Frutas - 350 ml - Maça', 'Lata', '350 ml', 'Maça', '4.211'),
                                                                                                  ('231776', 'Festival de Sabores - 700 ml - Açai', 'Garrafa', '700 ml', 'Açai', '13.312'),
                                                                                                  ('235653', 'Frescor do Verão - 350 ml - Manga', 'Lata', '350 ml', 'Manga', '3.8595'),
                                                                                                  ('243083', 'Festival de Sabores - 1,5 Litros - Maracujá', 'PET', '1,5 Litros', 'Maracujá', '10.512'),
                                                                                                  ('290478', 'Videira do Campo - 350 ml - Melância', 'Lata', '350 ml', 'Melância', '4.56'),
                                                                                                  ('326779', 'Linha Refrescante - 1,5 Litros - Manga', 'PET', '1,5 Litros', 'Manga', '16.5105'),
                                                                                                  ('394479', 'Sabor da Montanha - 700 ml - Cereja', 'Garrafa', '700 ml', 'Cereja', '8.409'),
                                                                                                  ('479745', 'Clean - 470 ml - Laranja', 'Garrafa', '470 ml', 'Laranja', '3.768'),
                                                                                                  ('520380', 'Pedaços de Frutas - 1 Litro - Maça', 'PET', '1 Litro', 'Maça', '12.011'),
                                                                                                  ('544931', 'Frescor do Verão - 350 ml - Limão', 'Lata', '350 ml', 'Limão', '2.4595'),
                                                                                                  ('695594', 'Festival de Sabores - 1,5 Litros - Açai', 'PET', '1,5 Litros', 'Açai', '28.512'),
                                                                                                  ('723457', 'Festival de Sabores - 700 ml - Maracujá', 'Garrafa', '700 ml', 'Maracujá', '4.912'),
                                                                                                  ('746596', 'Light - 1,5 Litros - Melância', 'PET', '1,5 Litros', 'Melância', '19.505'),
                                                                                                  ('773912', 'Clean - 1 Litro - Laranja', 'PET', '1 Litro', 'Laranja', '8.008'),
                                                                                                  ('783663', 'Sabor da Montanha - 700 ml - Morango', 'Garrafa', '700 ml', 'Morango', '7.709'),
                                                                                                  ('788975', 'Pedaços de Frutas - 1,5 Litros - Maça', 'PET', '1,5 Litros', 'Maça', '18.011'),
                                                                                                  ('812829', 'Clean - 350 ml - Laranja', 'Lata', '350 ml', 'Laranja', '2.808'),
                                                                                                  ('826490', 'Linha Refrescante - 700 ml - Morango/Limão', 'Garrafa', '700 ml', 'Morango/Limão', '6.3105'),
                                                                                                  ('838819', 'Clean - 1,5 Litros - Laranja', 'PET', '1,5 Litros', 'Laranja', '12.008');

INSERT INTO `vendedores` (`ID_MATRICULA`, `VENDEDOR`, `PERCENTUAL_COMISSAO`, `DATA_ADIMISSAO`, `DE_FERIAS`) VALUES ('203', 'Hollis Schoen', '0.4', '1983-11-20', b'0'),
                                                                                                                   ('211', 'Erica Tremblay DVM', '0', '1985-12-14', b'1'),
                                                                                                                   ('212', 'Kendall Simonis', '0.4', '2011-09-14', b'0'),
                                                                                                                   ('216', 'Sydnee Hartmann I', '0.7', '1996-08-15', b'1'),
                                                                                                                   ('217', 'Prof. Cheyenne Schuppe', '0.8', '2019-02-12', b'0'),
                                                                                                                   ('218', 'Deangelo Upton', '0.9', '1995-03-02', b'1'),
                                                                                                                   ('225', 'Elda Harvey', '1', '2010-02-15', b'0'),
                                                                                                                   ('229', 'Garrick Jakubowski', '0.9', '2017-03-10', b'1'),
                                                                                                                   ('231', 'Dayana Hansen', '0.6', '1998-01-12', b'1'),
                                                                                                                   ('235', 'Márcio Almeida Silva', '0.08', '2014-08-15', b'0'),
                                                                                                                   ('236', 'Cláudia Morais', '0.08', '2013-09-17', b'1'),
                                                                                                                   ('237', 'Roberta Martins', '0.11', '2017-04-18', b'1'),
                                                                                                                   ('238', 'Péricles Alves', '0.11', '2016-08-21', b'0'),
                                                                                                                   ('242', 'Dr. Bill Casper V', '0.9', '1976-02-15', b'0'),
                                                                                                                   ('243', 'Dr. Adan Auer V', '1', '1992-04-30', b'1'),
                                                                                                                   ('259', 'Stanford Krajcik', '0.1', '2001-08-09', b'1'),
                                                                                                                   ('268', 'Prof. Itzel Baumbach', '0.7', '1983-12-12', b'1'),
                                                                                                                   ('272', 'Carlo Cruickshank', '0.8', '2009-09-12', b'0'),
                                                                                                                   ('299', 'Elyssa O\'Hara', '0.6', '2018-11-18', b'0');
